from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class Cryptographer(Protocol):
    def encrypt(self, data: str) -> str: ...

    def encrypt_recursive(self, value: Any) -> Any: ...

    def decrypt(self, data: str) -> str: ...

    def decrypt_recursive(self, value: Any) -> Any: ...

    def get_hash(self, data: Any) -> str: ...

    def base62_encode(self, number: int) -> str: ...

    def is_encrypted(self, value: str) -> bool: ...

    def generate_short_code(self, data: Any, length: int = 6) -> str: ...
