from typing import Protocol, runtime_checkable


@runtime_checkable
class WaitlistDao(Protocol):
    async def exists(self, telegram_id: int) -> bool: ...

    async def add(self, telegram_id: int) -> None: ...

    async def get_members(self) -> list[int]: ...

    async def clear(self) -> None: ...
